machine_sounds_enabled = true
#Assembler Volume
# Default: 1.0
# Range: 0.0 ~ 5.0
assembler_volume = 1.0
#Blast Furnace Volume
# Default: 1.0
# Range: 0.0 ~ 5.0
blast_furnace_volume = 1.0
#Centrifuge Volume
# Default: 1.0
# Range: 0.0 ~ 5.0
centrifuge_volume = 1.0
#Chemical Reactor Volume
# Default: 1.0
# Range: 0.0 ~ 5.0
chemical_reactor_volume = 1.0
#Coke Oven Volume
# Default: 1.0
# Range: 0.0 ~ 5.0
coke_oven_volume = 1.0
#Compressor Volume
# Default: 1.0
# Range: 0.0 ~ 5.0
compressor_volume = 1.0
#Cutting Machine Volume
# Default: 1.0
# Range: 0.0 ~ 5.0
cutting_machine_volume = 1.0
#Distillation Tower Volume
# Default: 1.0
# Range: 0.0 ~ 5.0
distillation_tower_volume = 1.0
#Distillery Volume
# Default: 1.0
# Range: 0.0 ~ 5.0
distillery_volume = 1.0
#EBF Volume
# Default: 1.0
# Range: 0.0 ~ 5.0
electric_blast_furnace_volume = 1.0
#Electrolyzer Volume
# Default: 1.0
# Range: 0.0 ~ 5.0
electrolyzer_volume = 1.0
#Fission Reactor Volume
# Default: 1.0
# Range: 0.0 ~ 5.0
fission_reactor_volume = 1.0
#Fusion Reactor Volume
# Default: 1.0
# Range: 0.0 ~ 5.0
fusion_reactor_volume = 1.0
#Furnace Volume
# Default: 1.0
# Range: 0.0 ~ 5.0
furnace_volume = 1.0
#Heat Exchanger Volume
# Default: 1.0
# Range: 0.0 ~ 5.0
heat_exchanger_volume = 1.0
#Implosion Compressor Volume
# Default: 1.0
# Range: 0.0 ~ 5.0
implosion_compressor_volume = 1.0
#Macerator Volume
# Default: 1.0
# Range: 0.0 ~ 5.0
macerator_volume = 1.0
#Mixer Volume
# Default: 1.0
# Range: 0.0 ~ 5.0
mixer_volume = 1.0
#Oil Drilling Rig Volume
# Default: 1.0
# Range: 0.0 ~ 5.0
oil_drilling_rig_volume = 1.0
#Packer Volume
# Default: 1.0
# Range: 0.0 ~ 5.0
packer_volume = 1.0
#Polarizer Volume
# Default: 1.0
# Range: 0.0 ~ 5.0
polarizer_volume = 1.0
#Pressurizer Volume
# Default: 1.0
# Range: 0.0 ~ 5.0
pressurizer_volume = 1.0
#Quarry Volume
# Default: 1.0
# Range: 0.0 ~ 5.0
quarry_volume = 1.0
#Unpacker Volume
# Default: 1.0
# Range: 0.0 ~ 5.0
unpacker_volume = 1.0
#Vacuum Freezer Volume
# Default: 1.0
# Range: 0.0 ~ 5.0
vacuum_freezer_volume = 1.0
#Wiremill Volume
# Default: 1.0
# Range: 0.0 ~ 5.0
wiremill_volume = 1.0
#Wrench Volume
# Default: 1.0
# Range: 0.0 ~ 5.0
wrench_volume = 1.0
#Replicator Volume
# Default: 1.0
# Range: 0.0 ~ 5.0
replicator_volume = 1.0
